slice_name: "\uC11C\uBE44\uC2A4 \uC5C5\uC885\uC5D0 \uB530\uB978 \uC694\uC77C \uBCC4\
  \ \uB9E4\uCD9C \uAE08\uC561"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 24__table
  viz_type: echarts_timeseries_line
  x_axis: SERVICE
  x_axis_sort_asc: true
  x_axis_sort_series: sum
  x_axis_sort_series_ascending: false
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: MONDAY_PRICE_PER_CASE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 764
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uC6D4\uC694\uC77C"
    optionName: metric_55p7hz9e39y_7i6ag84q13m
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TUESDAY_PRICE_PER_CASE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 765
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uD654\uC694\uC77C"
    optionName: metric_qy42fbefjxr_wg10kneu8b
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: WEDNESDAY_PRICE_PER_CASE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 766
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uC218\uC694\uC77C"
    optionName: metric_onmfnmr6bdn_6g0b0f6958t
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: THURSDAY_PRICE_PER_CASE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 767
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uBAA9\uC694\uC77C"
    optionName: metric_0m73r2evjqm_mqga9erq8m
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: FRIDAY_PRICE_PER_CASE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 768
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uAE08\uC694\uC77C"
    optionName: metric_x7hrqt6kae_jyqd53urt3b
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: SATURDAY_PRICE_PER_CASE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 769
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uD1A0\uC694\uC77C"
    optionName: metric_16hc7w4bkhn_zsy2w2c1v4s
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: SUNDAY_PRICE_PER_CASE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 770
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uC77C\uC694\uC77C"
    optionName: metric_o4pmhrt4a6h_gvvkziskid
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 100
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  only_total: true
  area: false
  opacity: 0.2
  markerEnabled: false
  markerSize: 6
  zoomable: true
  minorTicks: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelRotation: 45
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: "{\"datasource\":{\"id\":24,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[],\"extras\":{\"having\":\"\",\"where\":\"\"},\"applied_time_extras\"\
  :{},\"columns\":[{\"columnType\":\"BASE_AXIS\",\"sqlExpression\":\"SERVICE\",\"\
  label\":\"SERVICE\",\"expressionType\":\"SQL\"}],\"metrics\":[{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"MONDAY_PRICE_PER_CASE\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":764,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uC6D4\uC694\uC77C\",\"optionName\":\"metric_55p7hz9e39y_7i6ag84q13m\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"TUESDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":765,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uD654\uC694\uC77C\",\"optionName\":\"metric_qy42fbefjxr_wg10kneu8b\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"WEDNESDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":766,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uC218\uC694\uC77C\",\"optionName\":\"metric_onmfnmr6bdn_6g0b0f6958t\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"THURSDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":767,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uBAA9\uC694\uC77C\",\"optionName\":\"metric_0m73r2evjqm_mqga9erq8m\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"FRIDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":768,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uAE08\uC694\uC77C\",\"optionName\":\"metric_x7hrqt6kae_jyqd53urt3b\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"SATURDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":769,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uD1A0\uC694\uC77C\",\"optionName\":\"metric_16hc7w4bkhn_zsy2w2c1v4s\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"SUNDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":770,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uC77C\uC694\uC77C\",\"optionName\":\"metric_o4pmhrt4a6h_gvvkziskid\"\
  }],\"orderby\":[[{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"MONDAY_PRICE_PER_CASE\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":764,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"DECIMAL(38, 0)\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"aggregate\":\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"\
  hasCustomLabel\":true,\"label\":\"\uC6D4\uC694\uC77C\",\"optionName\":\"metric_55p7hz9e39y_7i6ag84q13m\"\
  },false]],\"annotation_layers\":[],\"row_limit\":100,\"series_columns\":[],\"series_limit\"\
  :0,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{},\"time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\"\
  :{\"index\":[\"SERVICE\"],\"columns\":[],\"aggregates\":{\"\uC6D4\uC694\uC77C\"\
  :{\"operator\":\"mean\"},\"\uD654\uC694\uC77C\":{\"operator\":\"mean\"},\"\uC218\
  \uC694\uC77C\":{\"operator\":\"mean\"},\"\uBAA9\uC694\uC77C\":{\"operator\":\"mean\"\
  },\"\uAE08\uC694\uC77C\":{\"operator\":\"mean\"},\"\uD1A0\uC694\uC77C\":{\"operator\"\
  :\"mean\"},\"\uC77C\uC694\uC77C\":{\"operator\":\"mean\"}},\"drop_missing_columns\"\
  :false}},{\"operation\":\"flatten\"}]}],\"form_data\":{\"datasource\":\"24__table\"\
  ,\"viz_type\":\"echarts_timeseries_line\",\"x_axis\":\"SERVICE\",\"x_axis_sort_asc\"\
  :true,\"x_axis_sort_series\":\"sum\",\"x_axis_sort_series_ascending\":false,\"metrics\"\
  :[{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"MONDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":764,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uC6D4\uC694\uC77C\",\"optionName\":\"metric_55p7hz9e39y_7i6ag84q13m\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"TUESDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":765,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uD654\uC694\uC77C\",\"optionName\":\"metric_qy42fbefjxr_wg10kneu8b\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"WEDNESDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":766,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uC218\uC694\uC77C\",\"optionName\":\"metric_onmfnmr6bdn_6g0b0f6958t\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"THURSDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":767,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uBAA9\uC694\uC77C\",\"optionName\":\"metric_0m73r2evjqm_mqga9erq8m\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"FRIDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":768,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uAE08\uC694\uC77C\",\"optionName\":\"metric_x7hrqt6kae_jyqd53urt3b\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"SATURDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":769,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uD1A0\uC694\uC77C\",\"optionName\":\"metric_16hc7w4bkhn_zsy2w2c1v4s\"\
  },{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"SUNDAY_PRICE_PER_CASE\",\"description\"\
  :null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\":770,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uC77C\uC694\uC77C\",\"optionName\":\"metric_o4pmhrt4a6h_gvvkziskid\"\
  }],\"groupby\":[],\"adhoc_filters\":[],\"order_desc\":true,\"row_limit\":100,\"\
  truncate_metric\":true,\"show_empty_columns\":true,\"comparison_type\":\"values\"\
  ,\"annotation_layers\":[],\"forecastPeriods\":10,\"forecastInterval\":0.8,\"x_axis_title_margin\"\
  :15,\"y_axis_title_margin\":15,\"y_axis_title_position\":\"Left\",\"sort_series_type\"\
  :\"sum\",\"color_scheme\":\"supersetColors\",\"seriesType\":\"line\",\"only_total\"\
  :true,\"area\":false,\"opacity\":0.2,\"markerEnabled\":false,\"markerSize\":6,\"\
  zoomable\":true,\"minorTicks\":false,\"show_legend\":true,\"legendType\":\"scroll\"\
  ,\"legendOrientation\":\"top\",\"x_axis_time_format\":\"smart_date\",\"xAxisLabelRotation\"\
  :45,\"rich_tooltip\":true,\"tooltipTimeFormat\":\"smart_date\",\"y_axis_format\"\
  :\"SMART_NUMBER\",\"logAxis\":false,\"truncateXAxis\":true,\"y_axis_bounds\":[null,null],\"\
  extra_form_data\":{},\"dashboards\":[],\"force\":false,\"result_format\":\"json\"\
  ,\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 0c782bc2-0277-4f96-9790-3e3ddc25bb4d
version: 1.0.0
dataset_uuid: 1f61254a-5e08-4dd2-87fd-bbc2bedfb325
