slice_name: "TOP 10 \uCD1D\uD569 \uC18C\uBE44 \uC9C0\uC5ED"
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 26__table
  viz_type: pie
  slice_id: 76
  groupby:
  - REGION
  metric:
    aggregate: AVG
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: "\uCD1D \uB9E4\uCD9C \uD3C9\uADE0"
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 792
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: "AVG(\uCD1D \uB9E4\uCD9C \uD3C9\uADE0)"
    optionName: metric_e9lxta7d95i_bwohwkvpbkn
    sqlExpression: null
  adhoc_filters: []
  row_limit: 10
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: ',d'
  date_format: smart_date
  show_labels: true
  labels_outside: true
  label_line: true
  show_total: false
  outerRadius: 65
  donut: true
  innerRadius: 34
  extra_form_data: {}
  dashboards:
  - 8
query_context: "{\"datasource\":{\"id\":26,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[],\"extras\":{\"having\":\"\",\"where\":\"\"},\"applied_time_extras\"\
  :{},\"columns\":[\"REGION\"],\"metrics\":[{\"aggregate\":\"AVG\",\"column\":{\"\
  advanced_data_type\":null,\"certification_details\":null,\"certified_by\":null,\"\
  column_name\":\"\uCD1D \uB9E4\uCD9C \uD3C9\uADE0\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":792,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"AVG(\uCD1D \uB9E4\
  \uCD9C \uD3C9\uADE0)\",\"optionName\":\"metric_e9lxta7d95i_bwohwkvpbkn\",\"sqlExpression\"\
  :null}],\"orderby\":[[{\"aggregate\":\"AVG\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"\uCD1D\
  \ \uB9E4\uCD9C \uD3C9\uADE0\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":792,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"DECIMAL(38, 0)\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :false,\"label\":\"AVG(\uCD1D \uB9E4\uCD9C \uD3C9\uADE0)\",\"optionName\":\"metric_e9lxta7d95i_bwohwkvpbkn\"\
  ,\"sqlExpression\":null},false]],\"annotation_layers\":[],\"row_limit\":10,\"series_limit\"\
  :0,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{}}],\"form_data\":{\"datasource\":\"26__table\",\"viz_type\":\"pie\",\"slice_id\"\
  :76,\"groupby\":[\"REGION\"],\"metric\":{\"aggregate\":\"AVG\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"\uCD1D\
  \ \uB9E4\uCD9C \uD3C9\uADE0\",\"description\":null,\"expression\":null,\"filterable\"\
  :true,\"groupby\":true,\"id\":792,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"DECIMAL(38, 0)\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :false,\"label\":\"AVG(\uCD1D \uB9E4\uCD9C \uD3C9\uADE0)\",\"optionName\":\"metric_e9lxta7d95i_bwohwkvpbkn\"\
  ,\"sqlExpression\":null},\"adhoc_filters\":[],\"row_limit\":10,\"sort_by_metric\"\
  :true,\"color_scheme\":\"supersetColors\",\"show_labels_threshold\":5,\"show_legend\"\
  :true,\"legendType\":\"scroll\",\"legendOrientation\":\"top\",\"label_type\":\"\
  key\",\"number_format\":\",d\",\"date_format\":\"smart_date\",\"show_labels\":true,\"\
  labels_outside\":true,\"label_line\":true,\"show_total\":false,\"outerRadius\":65,\"\
  donut\":true,\"innerRadius\":34,\"extra_form_data\":{},\"dashboards\":[8],\"force\"\
  :false,\"result_format\":\"json\",\"result_type\":\"full\"},\"result_format\":\"\
  json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 31ecb5ab-3320-4eb1-a53e-a039e3693fa5
version: 1.0.0
dataset_uuid: 9346bf80-bd48-42f8-8f9e-82749f1c81f9
