slice_name: "\uC131\uBCC4 \uD589\uC815\uB3D9 \uAE38\uB2E8\uC704 \uC778\uAD6C TOP 10"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 41__table
  viz_type: echarts_timeseries_bar
  x_axis: REGION
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: sum
  x_axis_sort_series_ascending: false
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: POP_FEMALE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 844
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uC5EC\uC131 \uC774\uB3D9\uC778\uAD6C"
    optionName: metric_xrbaaxzguap_xwahshgbhbi
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: POP_MALE
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 843
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DECIMAL(38, 0)
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: SUM
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\uB0A8\uC131 \uC774\uB3D9\uC778\uAD6C"
    optionName: metric_ijer7p697qd_ab9khauom
  groupby: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: QUARTERS
    operator: ==
    operatorId: EQUALS
    comparator: '20234'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_eoagnttphq5_9r72x419fyn
  timeseries_limit_metric:
    expressionType: SQL
    sqlExpression: SUM(POP_MALE)+SUM(POP_FEMALE)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(POP_MALE)+SUM(POP_FEMALE)
    optionName: metric_idk0x2annp_leigv4s1hnb
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: echarts4Colors
  stack: null
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
query_context: "{\"datasource\":{\"id\":41,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[{\"col\":\"QUARTERS\",\"op\":\"==\",\"val\":\"20234\"}],\"\
  extras\":{\"time_grain_sqla\":\"P1D\",\"having\":\"\",\"where\":\"\"},\"applied_time_extras\"\
  :{},\"columns\":[{\"timeGrain\":\"P1D\",\"columnType\":\"BASE_AXIS\",\"sqlExpression\"\
  :\"REGION\",\"label\":\"REGION\",\"expressionType\":\"SQL\"}],\"metrics\":[{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"POP_FEMALE\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":844,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\uC5EC\uC131\
  \ \uC774\uB3D9\uC778\uAD6C\",\"optionName\":\"metric_xrbaaxzguap_xwahshgbhbi\"},{\"\
  expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"POP_MALE\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":843,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uB0A8\uC131 \uC774\uB3D9\uC778\uAD6C\",\"optionName\":\"metric_ijer7p697qd_ab9khauom\"\
  }],\"orderby\":[[{\"expressionType\":\"SQL\",\"sqlExpression\":\"SUM(POP_MALE)+SUM(POP_FEMALE)\"\
  ,\"column\":null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :false,\"label\":\"SUM(POP_MALE)+SUM(POP_FEMALE)\",\"optionName\":\"metric_idk0x2annp_leigv4s1hnb\"\
  },false]],\"annotation_layers\":[],\"row_limit\":10,\"series_columns\":[],\"series_limit\"\
  :0,\"series_limit_metric\":{\"expressionType\":\"SQL\",\"sqlExpression\":\"SUM(POP_MALE)+SUM(POP_FEMALE)\"\
  ,\"column\":null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :false,\"label\":\"SUM(POP_MALE)+SUM(POP_FEMALE)\",\"optionName\":\"metric_idk0x2annp_leigv4s1hnb\"\
  },\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{},\"time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\"\
  :{\"index\":[\"REGION\"],\"columns\":[],\"aggregates\":{\"\uC5EC\uC131 \uC774\uB3D9\
  \uC778\uAD6C\":{\"operator\":\"mean\"},\"\uB0A8\uC131 \uC774\uB3D9\uC778\uAD6C\"\
  :{\"operator\":\"mean\"}},\"drop_missing_columns\":false}},{\"operation\":\"flatten\"\
  }]}],\"form_data\":{\"datasource\":\"41__table\",\"viz_type\":\"echarts_timeseries_bar\"\
  ,\"x_axis\":\"REGION\",\"time_grain_sqla\":\"P1D\",\"x_axis_sort_asc\":true,\"x_axis_sort_series\"\
  :\"sum\",\"x_axis_sort_series_ascending\":false,\"metrics\":[{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"POP_FEMALE\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":844,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"SUM\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\uC5EC\uC131\
  \ \uC774\uB3D9\uC778\uAD6C\",\"optionName\":\"metric_xrbaaxzguap_xwahshgbhbi\"},{\"\
  expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"POP_MALE\",\"description\":null,\"\
  expression\":null,\"filterable\":true,\"groupby\":true,\"id\":843,\"is_certified\"\
  :false,\"is_dttm\":false,\"python_date_format\":null,\"type\":\"DECIMAL(38, 0)\"\
  ,\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\"\
  :\"SUM\",\"sqlExpression\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"\uB0A8\uC131 \uC774\uB3D9\uC778\uAD6C\",\"optionName\":\"metric_ijer7p697qd_ab9khauom\"\
  }],\"groupby\":[],\"adhoc_filters\":[{\"expressionType\":\"SIMPLE\",\"subject\"\
  :\"QUARTERS\",\"operator\":\"==\",\"operatorId\":\"EQUALS\",\"comparator\":\"20234\"\
  ,\"clause\":\"WHERE\",\"sqlExpression\":null,\"isExtra\":false,\"isNew\":false,\"\
  datasourceWarning\":false,\"filterOptionName\":\"filter_eoagnttphq5_9r72x419fyn\"\
  }],\"timeseries_limit_metric\":{\"expressionType\":\"SQL\",\"sqlExpression\":\"\
  SUM(POP_MALE)+SUM(POP_FEMALE)\",\"column\":null,\"aggregate\":null,\"datasourceWarning\"\
  :false,\"hasCustomLabel\":false,\"label\":\"SUM(POP_MALE)+SUM(POP_FEMALE)\",\"optionName\"\
  :\"metric_idk0x2annp_leigv4s1hnb\"},\"order_desc\":true,\"row_limit\":10,\"truncate_metric\"\
  :true,\"show_empty_columns\":true,\"comparison_type\":\"values\",\"annotation_layers\"\
  :[],\"forecastPeriods\":10,\"forecastInterval\":0.8,\"orientation\":\"vertical\"\
  ,\"x_axis_title_margin\":15,\"y_axis_title_margin\":15,\"y_axis_title_position\"\
  :\"Left\",\"sort_series_type\":\"sum\",\"color_scheme\":\"echarts4Colors\",\"stack\"\
  :null,\"only_total\":true,\"show_legend\":true,\"legendType\":\"scroll\",\"legendOrientation\"\
  :\"top\",\"x_axis_time_format\":\"smart_date\",\"y_axis_format\":\"SMART_NUMBER\"\
  ,\"truncateXAxis\":true,\"y_axis_bounds\":[null,null],\"rich_tooltip\":true,\"tooltipTimeFormat\"\
  :\"smart_date\",\"extra_form_data\":{},\"dashboards\":[],\"force\":false,\"result_format\"\
  :\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"\
  full\"}"
cache_timeout: null
uuid: 5213bcd7-7092-44e1-b2d7-30fea00edf7d
version: 1.0.0
dataset_uuid: 3387e195-284e-455c-bcfd-4e1b529e8b4f
